### PR TITLE
#320 Fix unexpected multiple selection

### LINKED ISSUE #320: Multiple selection in Safari (No pointer down event after losing focus)
在没有按shift的情况下，mac和ipad在操作rmp时，在进行站点操作时容易误认为是多选，浪费很多时间，望早日修复！谢谢！

Without pressing the Shift key, it is easy to mistakenly consider it as multiple selections when operating RMP on Mac and iPad during site operations, wasting a lot of time. I hope it can be fixed soon! Thank you!

### PR DESCRIPTION
**Pull request by langonginc**
Try to fix #320.

### CODE REVIEW

File: src/components/svg-canvas-graph.tsx [hunk 1]
```diff
@@ -151,7 +151,7 @@ const SvgCanvas = () => {
                 }
             } else {
                 // the node is just placed and should not trigger any save, only display the details
-                dispatch(addSelected(node));
+                dispatch(setSelected(new Set([node])));
```
Comment (langonginc) [inline src/components/svg-canvas-graph.tsx:154]: I have added it when it is created.

Comment (thekingofcity) [reply src/components/svg-canvas-graph.tsx:154]: Oh, I see, so here should be a no-op? Is only changing this line to `dispatch(setSelected(new Set([node])));` works the same as your previous change?

Comment (langonginc) [reply src/components/svg-canvas-graph.tsx:154]: No-op. 

It is different between this and the previous one. Nodes may not have generated when the pointer is up.

Comment (thekingofcity) [reply src/components/svg-canvas-graph.tsx:154]: That makes sense. Let's remove this line and update the comment. Since there has been no feedback until now, I believe you can merge this whenever you want :)

**Review by thekingofcity — APPROVED** [review]
LGTM

File: src/components/svg-canvas-graph.tsx (hunk 1 above)
Comment (langonginc) [reply src/components/svg-canvas-graph.tsx]: Done.
